apiVersion: kaito.sh/v1beta1
kind: Workspace
metadata:
  name: workspace-custom-llm
resource:
  labelSelector:
    matchLabels:
      apps: custom-llm
  preferredNodes:
    - kind-control-plane
inference:
  template:
    spec:
      containers:
        - name: custom-llm-container
          image: ghcr.io/sozercan/llama3.1:8b
          # image: ghcr.io/kaito-project/kaito/llm-reference-preset:latest # Kaito Reference Image
